name: Sync chatgpt/chatgpt-infinity/ to (adamlui/chatgpt-infinity/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/), then /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-infinity/(chrome|edge|opera)/extension/_locales/

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/chatgpt-infinity/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'kudo-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync chatgpt/chatgpt-infinity/ to adamlui/chatgpt-infinity/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/greasemonkey/

      - name: Sync chatgpt/chatgpt-infinity/ to adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/

      - name: Sync /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-infinity/(chrome|edge|opera)/extension/_locales/
        run: |
          for browser in chrome edge opera
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-infinity/greasemonkey/_locales/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/$browser/extension/_locales/"
          done

      - name: Push to adamlui/chatgpt-infinity
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '**'
          repository: adamlui/chatgpt-infinity

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'chatgpt-infinity/**'
          repository: adamlui/chatgpt-apps
