name: Sync chatgpt/duckduckgpt/ to (kudoai/duckduckgpt/greasemonkey/ && adamlui/chatgpt-apps/duckduckgpt/greasemonkey/)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/duckduckgpt/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'kudo-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout kudoai/duckduckgpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/duckduckgpt
          path: kudoai/duckduckgpt

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to to kudoai/duckduckgpt/docs/ && adamlui/chatgpt-apps/duckduckgpt/docs/
        run: cp -r -f -v ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/docs ${{ github.workspace }}/kudoai/duckduckgpt/ && cp -r -f -v ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/docs ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt/

      - name: Sync chatgpt/duckduckgpt/ to kudoai/duckduckgpt/greasemonkey/
        run: rsync -avhr --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ ${{ github.workspace }}/kudoai/duckduckgpt/greasemonkey/

      - name: Sync chatgpt/duckduckgpt/ to adamlui/chatgpt-apps/duckduckgpt/greasemonkey/
        run: rsync -avhr --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt/greasemonkey/

      - name: Push to kudoai/duckduckgpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '**'
          repository: kudoai/duckduckgpt

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'duckduckgpt/**'
          repository: adamlui/chatgpt-apps
