name: Sync youtube-classic/ to adamlui/youtube-classic/greasemonkey/

on:
  push:
    branches: [master]
    paths: [youtube-classic/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/youtube-classic
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/youtube-classic
          path: adamlui/youtube-classic

      - name: Sync docs to adamlui/youtube-classic/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/youtube-classic/docs \
            ${{ github.workspace }}/adamlui/youtube-classic/

      - name: Sync youtube-classic/ to adamlui/youtube-classic/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/youtube-classic/ \
            ${{ github.workspace }}/adamlui/youtube-classic/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/youtube-classic
        run: |
          cd ${{ github.workspace }}/adamlui/youtube-classic
          git add .
          git commit -n -m "$ESCAPED_MSG â†ž [auto-sync from \`adamlui/userscripts\`]" || true
          git push
