name: Sync changes to GitLab

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0

      - name: Push changes to gitlab.com/adamlui/userscripts
        env:
          GITLAB_SYNC_PAT: ${{ secrets.GITLAB_SYNC_PAT }}
        run: |
          git push --force -o ci.skip \
            https://oauth2:$GITLAB_SYNC_PAT@gitlab.com/adamlui/userscripts.git master
